### ISSUE TITLE
Licensing and traffic redirection issues

### ISSUE THREAD

**Issue by martenson** [galaxyproject/cargo-port#24]
Not sure if any of these two is a big issue but they should be considered.

* some binaries/sources have restrictive licenses that might prevent redistribution from depot
*  we will affect metrics of the tool creators/hosts by redirecting their traffic to us

**Comment by erasche** [comment]
@martenson yep. I was... honestly going to ignore these until they raised them.

If the binaries have restrictive licenses... I think this one is somewhat of a non-issue. All packages SHOULD have a f/oss license, and if they don't, people shouldn't be packaging them from some self hosted-copy of (e.g.) GATK2. All of the F/OSS licenses that are used allow re-hosting (IANAL, someone correct me if I'm wrong), so I don't believe this is an issue. Maybe we require PRs to include a pointer to the package license stating that it's F/OSS. 

Additional precedent is there for e.g. mirroring PyPi. People upload stuff there under a wide range of licenses, and those get mirrored without complaint by the community.

As for affecting metrics, this is a larger concern. JBrowse comes to mind since they use a URL that's clearly dedicated to tracking downloads. On one hand, we don't know if we trust them to keep that online forever, on the other hand, they probably want to know about their downloads. (That said, their public release version ships with a tracking pixel which I really really do not like).

If we just want to inform upstream that we're downloading, we could tally up the logs (e.g. per week/per month) and make that many download requests for the file at random times, and only for the first 1kb or so in order to not kill their servers, but to still show up in the logs. Thoughts?

**Comment by martenson** [comment]
Solution of faking the traffic probably wouldn't work as we will just skewer the metrics in favor of central PA's academic IPs. But I did think about streaming their files to /dev/null too :D

**Comment by bgruening** [comment]
@martenson interesting concerns. Thanks for that.
The licensing issue is a hard one I guess. We should state in the `contribution.md` file that we only can mirror files with a `good` license. And try to check the LICENSE file during our checks.

For the traffic issue I would actually try to convince people that CPC should be supported, by offering this as a service. We could simply offer download stats right? I could imagine that the bioarchive webfrontend shows download stats ...

**Comment by erasche** [comment]
@bgruening yeah, I asked @natefoo for example logs so I could write up a parser in https://github.com/erasche/community-package-cache/issues/20

**Comment by bgruening** [comment]
@erasche I hope there is already a parser. We are hopefully not the only one that want to track downloads :)

**Comment by erasche** [comment]
@bgruening i'm sure they're just regular nginx logs, I just need to know what they look like so I can write the grep/ack statements. Nothing complex :)

**Comment by erasche** [comment]
@martenson whenever we split the TS out, first thing I'd like to do is add a .shed.yml field for software license.

**Comment by erasche** [comment]
@bgruening has convinced me. We're fixing the traffic redirection issue by using upstream first. I've added a new column in cases where we should not use upstream because they've specifically requested that we don't (e.g. XZ) in a4d357233a21cab9629747c59435852bb34b49df

**Comment by martenson** [comment]
@erasche this also saves our bandwidth, good call imo
